version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 8
    groups:
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"
      pip-weekly:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 8
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
      npm-and-yarn:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 4
